<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:atom="http://www.w3.org/2005/Atom">
  <xsl:output method="html" encoding="utf-8"/>
  <xsl:template match="/">
    <html>
      <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title><xsl:value-of select="/atom:feed/atom:title"/></title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; color: #333; line-height: 1.6; padding: 20px; }
          .container { max-width: 800px; margin: 0 auto; background: #fff; border-radius: 8px; box-shadow: 0 2px 12px rgba(0,0,0,0.1); overflow: hidden; }
          .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #fff; padding: 40px 30px; }
          .header h1 { font-size: 24px; margin-bottom: 8px; }
          .header p { opacity: 0.85; font-size: 14px; }
          .header .meta { margin-top: 16px; font-size: 13px; opacity: 0.75; }
          .entry { padding: 20px 30px; border-bottom: 1px solid #eee; transition: background 0.2s; }
          .entry:hover { background: #fafafa; }
          .entry:last-child { border-bottom: none; }
          .entry h2 { font-size: 17px; margin-bottom: 6px; }
          .entry h2 a { color: #333; text-decoration: none; }
          .entry h2 a:hover { color: #667eea; }
          .entry .date { font-size: 12px; color: #999; margin-bottom: 8px; }
          .entry .summary { font-size: 14px; color: #666; line-height: 1.7; max-height: 80px; overflow: hidden; text-overflow: ellipsis; }
          .footer { text-align: center; padding: 20px; color: #999; font-size: 13px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1><xsl:value-of select="/atom:feed/atom:title"/></h1>
            <p><xsl:value-of select="/atom:feed/atom:subtitle"/></p>
            <div class="meta">
              <xsl:value-of select="/atom:feed/atom:updated"/> &middot;
              <xsl:value-of select="count(/atom:feed/atom:entry)"/> 篇文章
            </div>
          </div>
          <xsl:for-each select="/atom:feed/atom:entry">
            <div class="entry">
              <h2><a href="{atom:link/@href}"><xsl:value-of select="atom:title"/></a></h2>
              <div class="date"><xsl:value-of select="atom:updated"/></div>
              <div class="summary">
                <xsl:value-of select="atom:summary" disable-output-escaping="yes"/>
              </div>
            </div>
          </xsl:for-each>
          <div class="footer">RSS Feed &middot; Generated by Hexo</div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
